// src/pages/portfolio.vue
<script setup lang="ts">
import WithProfileLayout from "@/layouts/WithProfileLayout.vue";
import Timeline from "@/components/Timeline.vue";
import TimelineItem from "@/components/TimelineItem.vue";
import StudentCapIcon from "@/assets/svg/icons/student-cap.svg?raw";
</script>

<template>
    <WithProfileLayout>
        <Timeline :icon="StudentCapIcon" :title="$t('education')">
            <TimelineItem :title="$t('diploma.label')" :time_range="$t('2023')">
                {{ $t("diploma.description") }}
            </TimelineItem>
        </Timeline>
    </WithProfileLayout>
</template>

// src/pages/portfolio.svelte
<script lang="ts">
    import { _ } from "svelte-i18n";
    import Timeline from "@/components/Timeline.svelte";
    import TimelineItem from "@/components/TimelineItem.svelte";
    import StudentCapIcon from "@/svg/icons/student-cap.svg?raw";
</script>

<Timeline title={$_('education')} icon={StudentCapIcon}>
    <TimelineItem title={$_("diploma.label")} time_range={$_("2023")}>
        {$_("diploma.description")}
    </TimelineItem>
</Timeline>

<style lang="scss"></style>
