// src/components/sections/ThemeSwitcher.vue
<script setup lang="ts">
import Icon from "../Icon.vue";
import { useTheme } from "@/stores/theme";
import SunIcon from "@/assets/svg/icons/brightness.svg?raw";
import MoonIcon from "@/assets/svg/icons/moon-stars.svg?raw";
import { computed } from "vue";

const theme = useTheme();
const theme_icon = computed(() => theme.isDark ? SunIcon : MoonIcon);

</script>

<template>
    <Icon role="button" :class="['icon', { mc: !theme.isDark, sc: theme.isDark }]" :icon="theme_icon" :size="28"
        @click="theme.toggleTheme" />
</template>

<style scoped lang="scss">
.icon {
    @apply cursor-pointer;
}

// Moon Color
.mc {
    @apply text-slate-700;
}

// Sun color
.sc {
    @apply text-yellow-500;
}
</style>

// src/components/ThemeSwitcher.svelte
<script lang="ts">
    import MoonStarsIcon from '@/svg/icons/moon-stars.svg?raw';
    import SunIcon from '@/svg/icons/brightness.svg?raw';
    import Icon from '@/components/Icon.svelte';
    import { onMount } from 'svelte';
    import clsx from 'clsx';

    let isDarkMode: boolean;

    onMount(() => {
        isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;

        if (!localStorage.getItem('theme')) {
            localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
        }

        isDarkMode = localStorage.getItem('theme') === 'dark';
        isDarkMode && document.documentElement.classList.add('dark');
    });

    const handleToggleTheme = () => {
        isDarkMode = !isDarkMode;
        localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
        isDarkMode ? document.documentElement.classList.add('dark') : document.documentElement.classList.remove('dark');
    };

</script>

<button on:click={handleToggleTheme}>
    <Icon icon={isDarkMode ? SunIcon : MoonStarsIcon} size={25} class={clsx('cursor-pointer', isDarkMode ? 'text-yellow-500' : 'text-slate-700')} />
</button>
