// src/components/Timeline.svelte
<script lang="ts">
    import clsx from "clsx";
    import Icon from "./Icon.svelte";
    export let title: string;
    export let icon: string;
    let className: string = '';
    export {className as class};
</script>

<div class={clsx('title', className)}>
    <div class="icon">
        <Icon {icon} />
    </div>

    <span>{title}</span>
</div>

<div class="timeline">
    <slot />
</div>

<style lang="scss">
    @use "sass:math";

    $timeline_prl: math.div(2.75rem, 2);

    .title {
        @apply flex items-center gap-3;

        span {
            @apply font-bold text-2xl;
        }
    }

    .icon {
        @apply w-11 h-11 flex items-center justify-center rounded-2xl bg-slate-100;
        @apply text-center;
    }

    .timeline {
        @apply relative mt-5;
        padding-right: $timeline_prl;
        &::before {
            content: '';
            @apply border-r-2 rounded-full absolute border-slate-200;
            @apply w-0.5 h-6 -top-5;
            right: $timeline_prl;
        }
    }

    :global(.dark) {
        .icon {
            @apply bg-slate-800 shadow-dark;
        }

        .timeline {
            &::before {
                @apply border-slate-700
            }
        }
    }

    :global(html[dir="ltr"]) {
        .timeline {
            padding-right: unset;
            padding-left: $timeline_prl;

            &::before {
                right: unset;
                left: $timeline_prl;
            }
        }
    }
</style>

// src/components/Timeline.vue
<script setup lang="ts">
import { defineProps } from "vue";
import Icon from "@/components/Icon.vue";

const props = defineProps({
    icon: {
        type: String,
        required: true,
    },
    title: {
        type: String,
        required: true,
    },
});
</script>

<template>
    <div class="c">
        <div class="title">
            <div class="icon">
                <Icon :icon="props.icon" />
            </div>

            <span>{{ props.title }}</span>
        </div>

        <div class="timeline">
            <slot />
        </div>
    </div>
</template>

<style scoped lang="scss">
@use "sass:math";

$timeline_prl: math.div(2.75rem, 2);

// Continer
.c {
    @apply px-2 sm:px-0;
}

.title {
    @apply flex items-center gap-3;

    span {
        @apply font-bold text-2xl dark:text-white;
    }
}

.icon {
    @apply w-11 h-11 flex items-center justify-center rounded-2xl bg-slate-50;
    @apply text-center dark:bg-slate-800 dark:shadow-dark shadow-light dark:text-white;
}

.timeline {
    @apply relative mt-5;
    @apply rtl:pr-[#{$timeline_prl}] ltr:pl-[#{$timeline_prl}];

    &::before {
        content: '';
        @apply border-r-2 rounded-full absolute border-slate-200;
        @apply w-0.5 h-6 -top-5 dark:border-slate-700;
        @apply rtl:right-[#{$timeline_prl}] ltr:left-[#{$timeline_prl}];
    }
}
</style>
